databases:
  - name: netalog
    databaseName: netalog_db
    user: yuri_takagi
    region: singapore

services:
  - type: web
    name: netalog
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: netalog_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
